// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20230529051708_initials")]
    partial class initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = " Vineetrai826@gmail.com",
                            LastName = " Rai",
                            PhoneNumber = 452262502,
                            firstName = "Vineet"
                        },
                        new
                        {
                            Id = 2,
                            Email = " Mamta@826@gmail.com",
                            LastName = " Rai",
                            PhoneNumber = 452262502,
                            firstName = "Mamta"
                        },
                        new
                        {
                            Id = 3,
                            Email = " TusharRai826@gmail.com",
                            LastName = " Rai",
                            PhoneNumber = 452262502,
                            firstName = "Tushar"
                        },
                        new
                        {
                            Id = 4,
                            Email = " Nagarai826@gmail.com",
                            LastName = " Rai",
                            PhoneNumber = 452262502,
                            firstName = "Naga"
                        },
                        new
                        {
                            Id = 5,
                            Email = " Rajurai826@gmail.com",
                            LastName = " Rai",
                            PhoneNumber = 452262502,
                            firstName = "raju"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
